global:
  api-listen-addr: :5183
  timeout: 10s
  light-cache-size: 20
chains:
  - key: rly-testbed-key
    chain-id: lum-ibctest-1
    rpc-addr: http://127.0.0.1:26657
    account-prefix: lum
    gas-adjustment: 2.0
    gas-prices: 0.00001ulum
    trusting-period: 600s
  - key: rly-testbed-key
    chain-id: osmosis-ibctest-1
    rpc-addr: http://127.0.0.1:36657
    account-prefix: osmo
    gas-adjustment: 2.0
    gas-prices: 0.00001uosmo
    trusting-period: 180s
  - key: rly-testbed-key
    chain-id: ki-ibctest-1
    rpc-addr: http://127.0.0.1:46657
    account-prefix: ki
    gas-adjustment: 2.0
    gas-prices: 0.00001uxki
    trusting-period: 600s
  - key: rly-testbed-key
    chain-id: cosmos-ibctest-1
    rpc-addr: http://127.0.0.1:56657
    account-prefix: cosmos
    gas-adjustment: 2.0
    gas-prices: 0.00001uatom
    trusting-period: 600s
paths: {}
